services:
  - type: web
    name: https://corpus-mnc8.onrender.com/
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATA_URL
        sync: false
      - key: API_KEY
        sync: false
